/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: 腱鞘炎の人 (https://sketchfab.com/Kensyouen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/just-a-girl-b2359160a4f54e76b5ae427a55d9594d
Title: Just a girl
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

function Model({ onLoaded, ...props }) {
  const groupRef = useRef()
  const { nodes, materials } = useGLTF('/scene.gltf')

  useEffect(() => {
    if (!groupRef.current) return

    // Calculate bounding box of the entire model
    const box = new THREE.Box3().setFromObject(groupRef.current)
    const size = new THREE.Vector3()
    const center = new THREE.Vector3()
    box.getSize(size)
    box.getCenter(center)

    // Calculate scale to fit within target size (2.5 units)
    const maxDim = Math.max(size.x, size.y, size.z)
    const targetSize = 2.5
    const autoScale = maxDim > 0 ? targetSize / maxDim : 1

    // Apply auto-scale
    groupRef.current.scale.multiplyScalar(autoScale)

    // Re-center the model at origin
    const scaledCenter = center.multiplyScalar(autoScale)
    groupRef.current.position.sub(scaledCenter)

    // Recalculate after scaling for accurate info
    const finalBox = new THREE.Box3().setFromObject(groupRef.current)
    const finalSize = new THREE.Vector3()
    const finalCenter = new THREE.Vector3()
    finalBox.getSize(finalSize)
    finalBox.getCenter(finalCenter)

    // Calculate bounding sphere radius for camera positioning
    const radius = finalSize.length() / 2

    // Notify parent with model info
    if (onLoaded) {
      onLoaded({
        size: finalSize,
        center: finalCenter,
        radius,
        autoScale,
        boundingBox: finalBox
      })
    }
  }, [nodes, onLoaded])

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.lambert5SG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.lambert5SG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.lambert5SG} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.lambert6SG} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.lambert6SG} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.lambert6SG} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.lambert6SG} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.lambert6SG} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.lambert7SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')

export default Model